---
name: CPAN-LinksToDocs
version: 0.001
author:
  - 'Zoffix Znet <zoffix@cpan.org>'
abstract: get links to http://search.cpan.org documentation by giving short "tags"
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Carp: 1.04
build_requires:
  Test::More: 0
provides:
  CPAN::LinksToDocs:
    file: lib/CPAN/LinksToDocs.pm
    version: 0.001
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
